version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: fypnext
    steps:
      - node/install-packages:
          app-dir: ~/project/fypnext 
          pkg-manager: yarn 

workflows:
  example-workflow:
    jobs:
      - example-job