apiVersion: v1
kind: Pod
metadata:
   name: fyp-pod
spec:
   containers:
    - name: fyp-backend-container
      image: fyp-backend
      imagePullPolicy: IfNotPresent
      env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: password
      ports:
      - containerPort: 3000
