apiVersion: v1
kind: Pod
metadata:
   name: fyp-pod
spec:
   containers:
    - name: fyp-backend-container
      image: fyp-backend
      imagePullPolicy: IfNotPresent
      env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: host
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: port
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: database
        - name: DATABASE_URI
          valueFrom:
            configMapKeyRef:
              name: pgsecret
              key: uri
      ports:
      - containerPort: 3001